# Generated by Django 3.2.13 on 2022-05-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazakhstan_f', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
    ]
