# Generated by Django 3.2.13 on 2022-05-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazakhstan_f', '0002_auto_20220505_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tour name')),
                ('description', models.CharField(max_length=210, verbose_name='Description')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price cost')),
                ('date', models.CharField(blank=True, max_length=12, verbose_name='Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='image for tour')),
            ],
        ),
    ]
