# Generated by Django 3.2.13 on 2022-05-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazakhstan_f', '0003_tours'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFeedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=210, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=210, verbose_name='phone')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
